-- Hito 1: usuarios del sistema y su rol de acceso.
CREATE TABLE usuarios (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    email           VARCHAR(320) NOT NULL,
    password_hash   VARCHAR(100) NOT NULL,
    nombre          VARCHAR(150) NOT NULL,
    rol             VARCHAR(30)  NOT NULL,
    activo          BOOLEAN      NOT NULL DEFAULT TRUE,
    creado_en       TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualizado_en  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_usuarios PRIMARY KEY (id),
    -- Los correos se almacenan normalizados en minúsculas: el índice único basta.
    CONSTRAINT uq_usuarios_email UNIQUE (email),
    CONSTRAINT ck_usuarios_rol CHECK (rol IN ('ADMIN', 'USUARIO'))
);
