-- Hito 3: catálogos base de proveedores y productos.
-- Ambos usan borrado lógico (activo = false). Las restricciones UNIQUE abarcan también
-- los registros dados de baja: un NIT o SKU no se reutiliza sin reactivar el original.

CREATE TABLE proveedores (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nit             VARCHAR(20)  NOT NULL,
    razon_social    VARCHAR(200) NOT NULL,
    email           VARCHAR(320) NOT NULL,
    telefono        VARCHAR(20),
    direccion       VARCHAR(300),
    activo          BOOLEAN      NOT NULL DEFAULT TRUE,
    creado_en       TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualizado_en  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_proveedores PRIMARY KEY (id),
    CONSTRAINT uq_proveedores_nit UNIQUE (nit)
);

CREATE INDEX ix_proveedores_razon_social ON proveedores (razon_social);

CREATE TABLE productos (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    sku             VARCHAR(40)    NOT NULL,
    nombre          VARCHAR(150)   NOT NULL,
    descripcion     VARCHAR(1000),
    precio          NUMERIC(14, 2) NOT NULL,
    proveedor_id    BIGINT         NOT NULL,
    activo          BOOLEAN        NOT NULL DEFAULT TRUE,
    creado_en       TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualizado_en  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_productos PRIMARY KEY (id),
    CONSTRAINT uq_productos_sku UNIQUE (sku),
    CONSTRAINT ck_productos_precio CHECK (precio > 0),
    CONSTRAINT fk_productos_proveedor FOREIGN KEY (proveedor_id) REFERENCES proveedores (id)
);

CREATE INDEX ix_productos_proveedor_id ON productos (proveedor_id);
CREATE INDEX ix_productos_nombre ON productos (nombre);
