-- Hito 4: autenticación por nombre de usuario y registro cerrado por invitación.

-- ---------------------------------------------------------------------------
-- 1) usuarios.username: único y obligatorio.
--    Se añade como opcional, se rellena para los usuarios existentes y después
--    se vuelve NOT NULL + UNIQUE (añadirla NOT NULL directamente fallaría con datos).
-- ---------------------------------------------------------------------------
ALTER TABLE usuarios ADD COLUMN username VARCHAR(50);

-- Usuarios existentes: parte local del correo en minúsculas, '+' convertido en '_' y
-- recortada a 40 caracteres.  "Admin@Unisen.com" → "admin".
UPDATE usuarios
SET username = LOWER(REPLACE(SUBSTRING(email, 1, LEAST(POSITION('@' IN email) - 1, 40)), '+', '_'));

-- Si dos correos comparten parte local (ana@a.com y ana@b.com), el usuario más antiguo
-- la conserva y los demás reciben su id como sufijo ("ana_7").
UPDATE usuarios u
SET username = u.username || '_' || CAST(u.id AS VARCHAR(20))
WHERE EXISTS (SELECT 1 FROM usuarios o WHERE o.username = u.username AND o.id < u.id);

ALTER TABLE usuarios ALTER COLUMN username SET NOT NULL;
ALTER TABLE usuarios ADD CONSTRAINT uq_usuarios_username UNIQUE (username);

-- ---------------------------------------------------------------------------
-- 2) Códigos de invitación de un solo uso y con caducidad.
-- ---------------------------------------------------------------------------
CREATE TABLE codigos_invitacion (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    codigo              VARCHAR(32)              NOT NULL,
    fecha_expiracion    TIMESTAMP WITH TIME ZONE NOT NULL,
    usado               BOOLEAN                  NOT NULL DEFAULT FALSE,
    usuario_creador_id  BIGINT                   NOT NULL,
    -- Auditoría del canje: quién usó el código y cuándo.
    usado_por_id        BIGINT,
    fecha_uso           TIMESTAMP WITH TIME ZONE,
    creado_en           TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_codigos_invitacion PRIMARY KEY (id),
    CONSTRAINT uq_codigos_invitacion_codigo UNIQUE (codigo),
    CONSTRAINT fk_codigos_invitacion_creador FOREIGN KEY (usuario_creador_id) REFERENCES usuarios (id),
    CONSTRAINT fk_codigos_invitacion_usado_por FOREIGN KEY (usado_por_id) REFERENCES usuarios (id),
    -- Un código usado siempre registra quién y cuándo; uno sin usar, nunca.
    CONSTRAINT ck_codigos_invitacion_uso CHECK (
        (usado = TRUE AND usado_por_id IS NOT NULL AND fecha_uso IS NOT NULL)
        OR (usado = FALSE AND usado_por_id IS NULL AND fecha_uso IS NULL))
);

CREATE INDEX ix_codigos_invitacion_creador ON codigos_invitacion (usuario_creador_id);
