-- Solicitudes internas de compra (maestro-detalle) y rol GERENTE.
--
-- Una solicitud es lo que pide un trabajador; la orden de compra (lo que se envía al
-- proveedor) se modelará aparte. La solicitud es la raíz del agregado: sus líneas se crean y
-- se borran con ella.

-- GERENTE revisa solicitudes y mantiene catálogos, como ADMIN, pero no gestiona invitaciones.
ALTER TABLE usuarios DROP CONSTRAINT ck_usuarios_rol;
ALTER TABLE usuarios ADD CONSTRAINT ck_usuarios_rol CHECK (rol IN ('ADMIN', 'GERENTE', 'USUARIO'));

CREATE TABLE solicitudes (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY,
    usuario_id           BIGINT        NOT NULL,
    fecha                TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    estado               VARCHAR(20)   NOT NULL DEFAULT 'PENDIENTE',
    justificacion        VARCHAR(1000) NOT NULL,
    -- Revisión (aprobación o rechazo): quién, cuándo y por qué.
    revisado_por_id      BIGINT,
    fecha_revision       TIMESTAMP WITH TIME ZONE,
    comentario_revision  VARCHAR(500),

    CONSTRAINT pk_solicitudes PRIMARY KEY (id),
    CONSTRAINT fk_solicitudes_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios (id),
    CONSTRAINT fk_solicitudes_revisor FOREIGN KEY (revisado_por_id) REFERENCES usuarios (id),
    CONSTRAINT ck_solicitudes_estado CHECK (estado IN ('PENDIENTE', 'APROBADA', 'RECHAZADA')),
    -- Una solicitud revisada siempre tiene revisor y fecha; una pendiente, ninguno.
    CONSTRAINT ck_solicitudes_revision CHECK (
        (estado = 'PENDIENTE' AND revisado_por_id IS NULL AND fecha_revision IS NULL)
        OR (estado <> 'PENDIENTE' AND revisado_por_id IS NOT NULL AND fecha_revision IS NOT NULL)
    )
);

-- "Mis solicitudes" (USUARIO) y la bandeja de revisión por estado (ADMIN / GERENTE).
CREATE INDEX ix_solicitudes_usuario_fecha ON solicitudes (usuario_id, fecha);
CREATE INDEX ix_solicitudes_estado_fecha ON solicitudes (estado, fecha);

CREATE TABLE detalles_solicitud (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    solicitud_id  BIGINT  NOT NULL,
    producto_id   BIGINT  NOT NULL,
    cantidad      INTEGER NOT NULL,

    CONSTRAINT pk_detalles_solicitud PRIMARY KEY (id),
    CONSTRAINT fk_detalles_solicitud_solicitud FOREIGN KEY (solicitud_id)
        REFERENCES solicitudes (id) ON DELETE CASCADE,
    CONSTRAINT fk_detalles_solicitud_producto FOREIGN KEY (producto_id) REFERENCES productos (id),
    CONSTRAINT ck_detalles_solicitud_cantidad CHECK (cantidad > 0),
    -- Un producto aparece una sola vez por solicitud: se pide más cantidad, no otra línea.
    CONSTRAINT uq_detalles_solicitud_producto UNIQUE (solicitud_id, producto_id)
);

-- Comprobar si un producto está en solicitudes activas antes de darlo de baja.
CREATE INDEX ix_detalles_solicitud_producto ON detalles_solicitud (producto_id);
