-- SaaS B2B multi-empresa (base de datos y esquema compartidos) y nuevo RBAC.
--
-- Cada fila de negocio pertenece a una empresa (tenant) mediante empresa_id; Hibernate
-- filtra por esa columna con @TenantId. Los datos existentes se asignan a una "Empresa
-- Base" para que nada quede huérfano. Roles: SUPER_ADMIN (plataforma, sin empresa),
-- GERENTE (administra su empresa) y USUARIO.

-- ---------------------------------------------------------------------------
-- 1) Empresas (tenants) y la empresa base que recibe los datos actuales.
-- ---------------------------------------------------------------------------
CREATE TABLE empresas (
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nombre                    VARCHAR(200) NOT NULL,
    nit                       VARCHAR(20)  NOT NULL,
    activa                    BOOLEAN      NOT NULL DEFAULT TRUE,
    -- Código para unirse a la empresa (reservado para el alta de usuarios por empresa).
    codigo_invitacion_actual  VARCHAR(32),
    creado_en                 TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualizado_en            TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_empresas PRIMARY KEY (id),
    CONSTRAINT uq_empresas_nit UNIQUE (nit),
    CONSTRAINT uq_empresas_codigo_invitacion UNIQUE (codigo_invitacion_actual)
);

-- NIT provisional: actualízalo con el real de la empresa que ya usaba el sistema.
INSERT INTO empresas (nombre, nit) VALUES ('Empresa Base', '000000000-0');

-- ---------------------------------------------------------------------------
-- 2) Roles: ADMIN pasa a SUPER_ADMIN (operador de la plataforma, sin empresa).
-- ---------------------------------------------------------------------------
ALTER TABLE usuarios DROP CONSTRAINT ck_usuarios_rol;
UPDATE usuarios SET rol = 'SUPER_ADMIN' WHERE rol = 'ADMIN';
ALTER TABLE usuarios ADD CONSTRAINT ck_usuarios_rol CHECK (rol IN ('SUPER_ADMIN', 'GERENTE', 'USUARIO'));

-- ---------------------------------------------------------------------------
-- 3) usuarios.empresa_id: obligatoria salvo para SUPER_ADMIN, que nunca tiene empresa.
-- ---------------------------------------------------------------------------
ALTER TABLE usuarios ADD COLUMN empresa_id BIGINT;
UPDATE usuarios
SET empresa_id = (SELECT id FROM empresas WHERE nit = '000000000-0')
WHERE rol <> 'SUPER_ADMIN';
ALTER TABLE usuarios ADD CONSTRAINT fk_usuarios_empresa FOREIGN KEY (empresa_id) REFERENCES empresas (id);
ALTER TABLE usuarios ADD CONSTRAINT ck_usuarios_empresa CHECK (
    (rol = 'SUPER_ADMIN' AND empresa_id IS NULL) OR (rol <> 'SUPER_ADMIN' AND empresa_id IS NOT NULL));
-- Destino de las FK compuestas (empresa_id, usuario_id): un usuario solo actúa en su empresa.
ALTER TABLE usuarios ADD CONSTRAINT uq_usuarios_empresa_id UNIQUE (empresa_id, id);

-- ---------------------------------------------------------------------------
-- 4) proveedores: empresa obligatoria y NIT único por empresa (dos clientes del SaaS
--    pueden comprarle al mismo proveedor).
-- ---------------------------------------------------------------------------
ALTER TABLE proveedores ADD COLUMN empresa_id BIGINT;
UPDATE proveedores SET empresa_id = (SELECT id FROM empresas WHERE nit = '000000000-0');
ALTER TABLE proveedores ALTER COLUMN empresa_id SET NOT NULL;
ALTER TABLE proveedores ADD CONSTRAINT fk_proveedores_empresa FOREIGN KEY (empresa_id) REFERENCES empresas (id);
ALTER TABLE proveedores DROP CONSTRAINT uq_proveedores_nit;
ALTER TABLE proveedores ADD CONSTRAINT uq_proveedores_nit UNIQUE (empresa_id, nit);
ALTER TABLE proveedores ADD CONSTRAINT uq_proveedores_empresa_id UNIQUE (empresa_id, id);

-- ---------------------------------------------------------------------------
-- 5) productos: empresa obligatoria, SKU único por empresa y proveedor de la MISMA
--    empresa (FK compuesta: la base de datos impide cruzar datos entre tenants).
-- ---------------------------------------------------------------------------
ALTER TABLE productos ADD COLUMN empresa_id BIGINT;
UPDATE productos SET empresa_id = (SELECT id FROM empresas WHERE nit = '000000000-0');
ALTER TABLE productos ALTER COLUMN empresa_id SET NOT NULL;
ALTER TABLE productos ADD CONSTRAINT fk_productos_empresa FOREIGN KEY (empresa_id) REFERENCES empresas (id);
ALTER TABLE productos DROP CONSTRAINT uq_productos_sku;
ALTER TABLE productos ADD CONSTRAINT uq_productos_sku UNIQUE (empresa_id, sku);
ALTER TABLE productos DROP CONSTRAINT fk_productos_proveedor;
ALTER TABLE productos ADD CONSTRAINT fk_productos_proveedor
    FOREIGN KEY (empresa_id, proveedor_id) REFERENCES proveedores (empresa_id, id);

-- ---------------------------------------------------------------------------
-- 6) solicitudes: empresa obligatoria y solicitante de la misma empresa.
-- ---------------------------------------------------------------------------
ALTER TABLE solicitudes ADD COLUMN empresa_id BIGINT;
UPDATE solicitudes SET empresa_id = (SELECT id FROM empresas WHERE nit = '000000000-0');
ALTER TABLE solicitudes ALTER COLUMN empresa_id SET NOT NULL;
ALTER TABLE solicitudes ADD CONSTRAINT fk_solicitudes_empresa FOREIGN KEY (empresa_id) REFERENCES empresas (id);
ALTER TABLE solicitudes DROP CONSTRAINT fk_solicitudes_usuario;
ALTER TABLE solicitudes ADD CONSTRAINT fk_solicitudes_usuario
    FOREIGN KEY (empresa_id, usuario_id) REFERENCES usuarios (empresa_id, id);
CREATE INDEX ix_solicitudes_empresa_fecha ON solicitudes (empresa_id, fecha);

-- ---------------------------------------------------------------------------
-- 7) codigos_invitacion: cada código da acceso a una empresa concreta.
-- ---------------------------------------------------------------------------
ALTER TABLE codigos_invitacion ADD COLUMN empresa_id BIGINT;
UPDATE codigos_invitacion SET empresa_id = (SELECT id FROM empresas WHERE nit = '000000000-0');
ALTER TABLE codigos_invitacion ALTER COLUMN empresa_id SET NOT NULL;
ALTER TABLE codigos_invitacion ADD CONSTRAINT fk_codigos_invitacion_empresa
    FOREIGN KEY (empresa_id) REFERENCES empresas (id);
CREATE INDEX ix_codigos_invitacion_empresa ON codigos_invitacion (empresa_id);
